// include faultable library gates	
#include "bufg.h"
#include "notg.h"
#include "and_n.h"
#include "or_n.h"
#include "nand_n.h"
#include "nor_n.h"
#include "xor_n.h"
#include "xnor_n.h"
#include "pin.h"
#include "pout.h"
#include "dff.h"
#include "DFF_NP.h"
